export const PLAYLIST_CONTEXT = {
  GET_PLAYLIST_BY_ID: "GET_PLAYLIST_BY_ID",
  CREATE_PLAYLIST: "CREATE_PLAYLIST",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",
  ADD_TRACK: "ADD_TRACK",
  REMOVE_TRACK: "REMOVE_TRACK",
};
